version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/quickstart/1-browser-to-browser"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "@fluencelabs/fluence"
      - dependency-name: "@fluencelabs/fluence-network-environment"
      - dependency-name: "@fluencelabs/aqua"
      - dependency-name: "@fluencelabs/aqua-lib"

  - package-ecosystem: "npm"
    directory: "/quickstart/3-browser-to-service"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "@fluencelabs/fluence"
      - dependency-name: "@fluencelabs/fluence-network-environment"
      - dependency-name: "@fluencelabs/aqua"
      - dependency-name: "@fluencelabs/aqua-lib"

  - package-ecosystem: "npm"
    directory: "/fluence-js-examples/hello-world"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "@fluencelabs/fluence"
      - dependency-name: "@fluencelabs/fluence-network-environment"
      - dependency-name: "@fluencelabs/aqua"
      - dependency-name: "@fluencelabs/aqua-lib"

  - package-ecosystem: "npm"
    directory: "/fluence-js-examples/browser-example"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "@fluencelabs/fluence"
      - dependency-name: "@fluencelabs/fluence-network-environment"
      - dependency-name: "@fluencelabs/aqua"
      - dependency-name: "@fluencelabs/aqua-lib"

  - package-ecosystem: "npm"
    directory: "/fluence-js-examples/node-example"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "@fluencelabs/fluence"
      - dependency-name: "@fluencelabs/fluence-network-environment"
      - dependency-name: "@fluencelabs/aqua"
      - dependency-name: "@fluencelabs/aqua-lib"

  - package-ecosystem: "npm"
    directory: "/aqua-examples/aqua-ipfs-integration"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "@fluencelabs/fluence"
      - dependency-name: "@fluencelabs/fluence-network-environment"
      - dependency-name: "@fluencelabs/aqua"
      - dependency-name: "@fluencelabs/aqua-lib"

  - package-ecosystem: "npm"
    directory: "/aqua-examples/echo-greeter/client-peer"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "@fluencelabs/fluence"
      - dependency-name: "@fluencelabs/fluence-network-environment"
      - dependency-name: "@fluencelabs/aqua"
      - dependency-name: "@fluencelabs/aqua-lib"

  - package-ecosystem: "npm"
    directory: "/aqua-examples/price-oracle/client-peer"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "@fluencelabs/fluence"
      - dependency-name: "@fluencelabs/fluence-network-environment"
      - dependency-name: "@fluencelabs/aqua"
      - dependency-name: "@fluencelabs/aqua-lib"
