version: 2
updates:

  - package-ecosystem: "npm"
    directory: "/quickstart/1-browser-to-browser"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "@fluencelabs/fluence"
      - dependency-name: "@fluencelabs/fluence-network-environment"
      - dependency-name: "@fluencelabs/aqua"
      - dependency-name: "@fluencelabs/aqua-lib"
