modules_dir = "artifacts/"

[[module]]
name = "sqlite3"
max_heap_size = "100  KiB"
logger_enabled = false

[module.wasi]
preopened_files = ["/tmp"]
mapped_dirs = { "tmp" = "/tmp" }

[[module]]
name = "sqlite_test"
max_heap_size = "10  KiB"
logger_enabled = false

[module.wasi]
preopened_files = ["/tmp"]
mapped_dirs = { "tmp" = "/tmp" }
