modules_dir = "artifacts"

[[module]]
name = "curl_adapter"
max_heap_size = "100 KiB"
logger_enabled = true

[module.mounted_binaries]
curl = "/usr/bin/curl"

[[module]]
name = "ceramic_adapter_custom"
max_heap_size = "50 Kib"
logger_enabled = true

[module.mounted_binaries]
ceramic = "/Users/bebo/.nvm/versions/node/v14.16.0/bin/ceramic"
