name: "check-deploy"

on:
  push:
    # branches:
    #   - "master"

jobs:
  check-deployment:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ~/.cargo/bin
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      
      - run: docker run -d --rm -e RUST_LOG="info" -p 1210:1210 -p 4310:4310 fluencelabs/fluence -t 1210 -w 4310 -k gKdiCSUr1TFGFEgu2t8Ch1XEUsrN5A2UfBLjSZvfci9SPR3NvZpACfcpPGC3eY4zma1pk7UvYv5zb1VjvPHwCjj --local
      
      - name: Download marine
        run: sudo bash $GITHUB_WORKSPACE/.github/download_marine.sh
      
      - name: Install Rust
        run: |
          rustup toolchain install nightly-2021-04-24-x86_64-unknown-linux-gnu
          rustup default nightly-2021-04-24-x86_64-unknown-linux-gnu
          rustup target add wasm32-wasi --toolchain nightly-2021-04-24-x86_64-unknown-linux-gnu
  
      - uses: actions/cache@v2
        with:
            path: ~/.npm
            key: ${{ runner.os }}-v1-node-14-${{ hashFiles('**/package-lock.json') }}
            restore-keys: |
                ${{ runner.os }}-v1-node-14
      
      - name: Setup Node.js 14
        uses: actions/setup-node@v1
        with:
            node-version: 14

      - run: npm install -g @fluencelabs/fldist

      - name: "Check call_parameters deployment"
        run: |
          set -x
          NODE="/ip4/127.0.0.1/tcp/4310/ws/p2p/12D3KooWKEprYXUXqoV5xSBeyqrWLpQLLH4PXfvVkDJtmcqmh5V3"
          SERVICE_ID=`./deploy.sh $NODE`

          echo "
service CallParameters:
  call_parameters() -> string

func call(service_id: string) -> string:
  on HOST_PEER_ID:
    CallParameters service_id
    r <- CallParameters.call_parameters()
    <- r
" > /tmp/call.aqua
          RESULT=$(aqua run --addr $NODE --sk qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqo= -f 'call(service_id)' -d '{"service_id": "'$SERVICE_ID'"}' --input /tmp/call.aqua)
          
          EXPECTED_PEER_ID=$(echo -e "$RESULT" | sed -n '1p' | grep -o '12D3.*')
          RESULT_PEER_ID=$(echo -e "$RESULT" | sed -n '2p' | tr -d \")
          if [ "$EXPECTED_PEER_ID" -neq "$RESULT_PEER_ID" ]; then
            echo "Expected $EXPECTED_PEER_ID, got $RESULT_PEER_ID"
            exit 1
          fi

          RESULT_SERVICE_ID=$(echo -e "$RESULT" | sed -n '3p')
          if [ "$SERVICE_ID" -neq "$RESULT_SERVICE_ID" ]; then
            echo "Expected $SERVICE_ID, got $RESULT_SERVICE_ID"
            exit 1
          fi

          aqua dist remove --addr $NODE --sk qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqo= --id "$SERVICE_ID"
        working-directory: marine-examples/call_parameters

